---
title: "HW7: Bayes inference"
output: html_document
date: "2026-06-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. Bayes factor

В одном эксперименте испытуемым давали прочитать предложения на языке X в режиме свободного чтения (self-paced reading). Чтение начиналось со звездочки, потом появлялось первое слово, потом второе (а первое закрывалось), по нажатию клавиши. В конце испытуемые должны были ответить на вопрос на понимание смысла предложения. Задача исследования была проверить, что ошибки в согласовании существительного и зависимого от него придаточного предложения будут иметь эффект на время прочтения предложения, а также на время ответа на вопрос. Кроме того, у исследователей была гипотеза, что этот эффект будет неодинаковым у носителей языка (L1) и в группе L2 -- у изучающих язык на уровне B2.  
Пример ошибки согласования: *Я увидел девушек, танцующую при свете луны*.  

1.1 Сформулируйте три пары гипотез исследования (H0 и H1). Гипотез может быть больше, но давайте остановимся на трех.

```{text 1.1}
1. (переменная - непрерывно-числовая):  
2. (переменная - непрерывно-числовая):  
3. (переменная - категориальная):  
```

1.2 Вам нужно задать информированный приор как разницу в скорости чтения между группами L1 и L2 (в миллисекундах, время чтения одного слога). Предложите пару идей, откуда специалисты такое значение получают. Сами параметры указывать не нужно.  

```{text 1.2}

```

1.3 В результате эксперимента исследователи выяснили, что для групп L1 и L2 разница в скорости чтения на отрезке между целевым существительным и согласуемым глаголом составила 27,5 миллисекунд, 95% CredI [0.24,0.31], BF10 = 0.89. Запишите интерпретацию значения байесовского фактора. Не забудьте, что и тут нужно указать конкретную пару гипотез, которая оценивается.     

```{text 1.3}

```


### 2. Байесовская регрессия  

Ниже дан вывод модели на основе вымышленного набора данных, который предсказывает время реакции при прослушивании аудио-стимула (слова) в зависимости от количества слогов. Интерпретируйте вывод модели:  

```{text}
##  Family: gaussian 
##  Links: mu = identity 
##  Formula: RT ~ 1 + n_syl 
##   Data: df (Number of observations: 378) 
##   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
##          total post-warmup draws = 4000
## 
## Regression Coefficients:
##           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## Intercept     6.59      0.07     6.49     6.74 1.00     3971     3420
## n_syl         0.13      0.01     0.12     0.14 1.00     3517     2972
##
## Further Distributional Parameters:
##           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sigma         0.99      0.03     0.94     1.05 1.00     4206     2764
## 
## Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
## and Tail_ESS are effective sample size measures, and Rhat is the potential
## scale reduction factor on split chains (at convergence, Rhat = 1).
```

2.1 Запишите свои выводы. Обратите внимание на интерпретацию R-hat. Подумайте, какая информация в выводе моделей позволяет утверждать, что время реакции зависит (или не зависит) от количества слогов.

```{text}


```

### 3. Дополнительное задание  

1. Пользуясь тетрадкой с семинара, постройте линейную байесовскую регрессию для первых 25 точек наблюдения датасета `english`. Формула модели `RTlexdec ~ 1 + WrittenFrequency` (без центрирования переменной), прайор - неинформативный (можно использовать параметры из тетрадки).   
2. С помощью функции `plot()` визуально интерпретируйте базовые диагностические данные модели.  
3. Постройте график 95% CI. 
4. Постройте график PI.  
5. Постройте график spaghetti plot.  
6. Интерпретируйте вывод самой модели (доверительные интервалы коэффициентов, R-hat и т. д.).  
7. Сформулируйте общий вывод.  
8. Сравните то, что вы получили, с данными из тетрадки для регрессии для 250 точек наблюдения. Сформулируйте выводы, объясните наблюдаемые различия, если они есть.  

